runtime: python313-slim

entrypoint: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT

env_variables:
  SECRET_KEY: "SECRET_KEY"
  GEMINI_API_KEY: "GEMINI_API_KEY"
  MYSQL_USER: "MYSQL_USER"
  MYSQL_PASSWORD: "MYSQL_PASSWORD"
  MYSQL_SERVER: "MYSQL_SERVER"
  MYSQL_PORT: "MYSQL_PORT"
  MYSQL_DB: "MYSQL_DB"
  VITE_API_BASE_URL: "VITE_API_BASE_URL"
  server_key: "MIDTRANS_SERVER_KEY"
  client_key: "MIDTRANS_CLIENT_KEY"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
instance_class: F1