steps:
  # Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/delta-chess-482214-p4/tiprepo', '.']
  # Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/delta-chess-482214-p4/tiprepo']
  # Deploy to Cloud Run
- name: 'gcr.io/google-cloudsdk/cloudsdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'nama-service'
  - '--image'
  - 'asia-southeast1-docker.pkg.dev/delta-chess-482214-p4/tiprepo'
  - '--region'
  - 'lokasi-cloud-run'
  - '--platform=managed'
images:
- 'asia-southeast1-docker.pkg.dev/delta-chess-482214-p4/tiprepo'
